name: MicroQuests
version: '1.7'
main: com.trenton.microquests.MicroQuests
api-version: '1.21'
authors: [ Trent ]
softdepend: [ Vault ]
commands:
  quest:
    description: Manage MicroQuests competitions
    usage: /<command> [optout|status]